# Generated by Django 5.2.3 on 2025-07-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon'),
        ),
    ]
