# Generated by Django 5.2.3 on 2025-07-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boost', '0002_alter_challenge_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_read',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
