# Generated by Django 5.2.3 on 2025-07-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boost', '0003_challenge_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
